### PR TITLE
Adding 1924 Lovecraft stories

### PR DESCRIPTION
**Pull request by nczaban**
The Hound
Hypnos
Imprisoned with the Pharaohs
The Rats in the Walls
The Picture in the House
Facts Concerning the Late Arthur Jermyn and his Family

### CODE REVIEW

**Comment by acabal** [comment]
Can you run `se lint` and fix the issues it raises?

**Comment by nczaban** [comment]
Done

**Comment by acabal** [comment]
Additionally, `se clean` has to be run again, and `se typogrify` makes changes to The Hound

**Comment by nczaban** [comment]
Done

**Comment by acabal** [comment]
Can you also add the sources for the transcriptions/page scans to content.opf?

**Comment by nczaban** [comment]
Done

**Comment by acabal** [comment]
Great work, thanks!

**Comment by acabal** [comment]
One more thing, you should add yourself to the content.opf metadata as a contributor. You can copy Evan Hall's block.

**Pull request merged**
